version: 2.1

orbs:
  node: circleci/node@5.0.2 # use the node orb to install node and npmm
  aws-ecr: circleci/aws-ecr@8.1.2 # use the AWS ECR orb
  aws-ecs: circleci/aws-ecs@3.2.0 # use the AWS ECS orb
  aws-cli: circleci/aws-cli@3.1.1 # use the AWS CLI orb
  aws-ec2: circleci/aws-ec2@2.2.0
  
jobs:
  build_and_test:
    executor: node/default # use the default executor defined within the orb
#     working_directory: ~/ExampleApplication/
     
    steps:
      - run:
          name: Setting Directory 
          command : ls
         
      - checkout
      - node/install-packages: # install dependencies with caching
           app-dir: ExampleApplication/
           
      - run:
          name: Build app
          command: |
            cd ExampleApplication
            npm install  
      - run:
          name: Test app
          command: |
            cd ExampleApplication
            npm test 
 
  verify-deployment:
    executor: aws-cli/default
    steps:
      - aws-ec2/deploy:
          filters:
            branches:
              only:
                - master
          target-tag: latest
          source: .
          destination: /var/www/html
          aws-region: ${AWS_DEFAULT_REGION}
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - verify-deployment:
          requires:
            - aws-ecs/deploy-service-update
