version: 2.1
orbs:
  node: circleci/node@5.0.2 # use the node orb to install node and npm
jobs:
  build_and_test:
    executor: node/default # use the default executor defined within the orb
#     working_directory: ~/ExampleApplication/
     
    steps:
      - run:
          name: Setting Directory 
          command : ls
         
      - checkout
      - node/install-packages # install dependencies with caching
      - run:
          name: Build app
          command: npm run build # run your build script
      - run:
          name: Test app
          command: npm test # run your test script
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy app
          command: npm run deploy # run your deploy script
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy after build and test job is successful
