version: 2.1

orbs:
  node: circleci/node@5.0.2 # use the node orb to install node and npmm
  
jobs:
  build_and_test:
    executor: node/default # use the default executor defined within the orb
#     working_directory: ~/ExampleApplication/
     
    steps:
      - run:
          name: Setting Directory 
          command : ls
         
      - checkout
      - node/install-packages: # install dependencies with caching
           app-dir: ExampleApplication/
           
      - run:
          name: Build app
          command: |
            cd ExampleApplication
            npm install  
      - run:
          name: Test app
          command: |
            cd ExampleApplication
            npm test 
      - run:
          name: Deployment
          command: |
            cd ExampleApplication
            ssh -i ${AWS_SECRET_ACCESS_KEY} -o StrictHostKeyChecking=no ec2-user@ec2-3-145-59-151.us-east-2.compute.amazonaws.com 'cd gitproject/ExampleApplication && git pull && cd ExampleApplication && npm install && exit'
            
            
 
 

          

workflows:
  build_test_deploy:
    jobs:
      - build_and_test

